sudo: required

services:
  - docker
env:
  matrix:
    - POLYNOTE_VERSION=0.3.6 SPARK_VERSION=2.9.0-2.4.3 HADOOP_VERSION=hadoop-2.9 SCALA_VERSION=2.11
    - POLYNOTE_VERSION=0.3.6 SPARK_VERSION=2.9.0-2.4.3 HADOOP_VERSION=hadoop-2.9 SCALA_VERSION=2.12
    - POLYNOTE_VERSION=0.3.6 SPARK_VERSION=2.9.0-2.4.3 HADOOP_VERSION=hadoop-2.7 SCALA_VERSION=2.11
    - POLYNOTE_VERSION=0.3.6 SPARK_VERSION=2.9.0-2.4.3 HADOOP_VERSION=hadoop-2.7 SCALA_VERSION=2.12    

script:
  - docker build 
    --build-arg POLYNOTE_VERSION=${POLYNOTE_VERSION} 
    --build-arg SPARK_VERSION=${SPARK_VERSION}
    --build-arg HADOOP_VERSION=${HADOOP_VERSION}    
    --build-arg SCALA_VERSION=${SCALA_VERSION} 
    --tag ${DOCKER_USERNAME}/${IMAGE}:${POLYNOTE_VERSION}-${SPARK_VERSION}-scala-${SCALA_VERSION}-${HADOOP_VERSION}
    docker/.

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${POLYNOTE_VERSION}-${SPARK_VERSION}-scala-${SCALA_VERSION}-${HADOOP_VERSION}
