sudo: required

services:
  - docker
env:
  matrix:
    - POLYNOTE_VERSION=0.3.2 SPARK_VERSION=2.9.0-2.4.3-scala-2.11-hadoop-2.9 

script:
  - docker build 
    --build-arg POLYNOTE_VERSION=${POLYNOTE_VERSION} 
    --build-arg SPARK_VERSION=${SPARK_VERSION} 
    --tag ${DOCKER_USERNAME}/${IMAGE}:${POLYNOTE_VERSION}-${SPARK_VERSION}
    docker/.

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${POLYNOTE_VERSION}-${SPARK_VERSION}
